"""
Oracle 테이블 재생성 + SQLite 마이그레이션
실행: python recreate_oracle.py
"""
import os
from datetime import datetime, timezone
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
import oracledb

load_dotenv()

dsn = '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=58.120.31.229)(PORT=1522))(CONNECT_DATA=(SID=CSONLINE)))'
con = oracledb.connect(user='worldcup', password='Gtplus#700', dsn=dsn)
cur = con.cursor()
print("Oracle 연결 성공")

# ── 1. 기존 테이블 DROP ───────────────────────────────────────────────────
print("\n[1] 기존 테이블 삭제...")
for tbl in ['bets', 'matches', 'users']:
    try:
        cur.execute(f'DROP TABLE {tbl} CASCADE CONSTRAINTS')
        print(f'  {tbl} 삭제')
    except Exception as e:
        print(f'  {tbl} 없음 (스킵)')
con.commit()

# ── 2. 테이블 재생성 (IDENTITY 포함) ─────────────────────────────────────
print("\n[2] 테이블 재생성...")

cur.execute("""
CREATE TABLE users (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    email         VARCHAR2(320) NOT NULL UNIQUE,
    nickname      VARCHAR2(100) NOT NULL UNIQUE,
    hashed_password VARCHAR2(256) NOT NULL,
    points        NUMBER DEFAULT 100000 NOT NULL,
    is_admin      NUMBER(1) DEFAULT 0 NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
""")
print("  users 생성")

cur.execute("""
CREATE TABLE matches (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    home_team     VARCHAR2(100) NOT NULL,
    away_team     VARCHAR2(100) NOT NULL,
    home_flag     VARCHAR2(20),
    away_flag     VARCHAR2(20),
    match_date    TIMESTAMP WITH TIME ZONE NOT NULL,
    venue         VARCHAR2(200) NOT NULL,
    city          VARCHAR2(100) NOT NULL,
    stage         VARCHAR2(50) NOT NULL,
    group_name    VARCHAR2(10),
    status        VARCHAR2(20) DEFAULT 'upcoming' NOT NULL,
    home_score    NUMBER,
    away_score    NUMBER,
    is_korea_match NUMBER(1) DEFAULT 0 NOT NULL,
    home_slot     VARCHAR2(100),
    away_slot     VARCHAR2(100)
)
""")
print("  matches 생성")

cur.execute("""
CREATE TABLE bets (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id       NUMBER NOT NULL REFERENCES users(id),
    match_id      NUMBER NOT NULL REFERENCES matches(id),
    prediction    VARCHAR2(20) NOT NULL,
    amount        NUMBER NOT NULL,
    payout        NUMBER,
    status        VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
""")
print("  bets 생성")
con.commit()

# ── 3. SQLite 데이터 읽기 ─────────────────────────────────────────────────
print("\n[3] SQLite에서 데이터 읽는 중...")
sqlite_engine = create_engine("sqlite:///./worldcup.db", connect_args={"check_same_thread": False})
src = sessionmaker(bind=sqlite_engine)()

def parse_dt(s):
    if not s:
        return None
    s = str(s).split(".")[0]
    dt = datetime.strptime(s, "%Y-%m-%d %H:%M:%S")
    return dt.replace(tzinfo=timezone.utc)

# ── 4. Matches 삽입 ───────────────────────────────────────────────────────
matches = src.execute(text(
    "SELECT id, home_team, away_team, home_flag, away_flag, match_date, "
    "venue, city, stage, group_name, status, home_score, away_score, "
    "is_korea_match, home_slot, away_slot FROM matches"
)).fetchall()

cur.executemany("""
    INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, match_date,
        venue, city, stage, group_name, status, home_score, away_score,
        is_korea_match, home_slot, away_slot)
    VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13,:14,:15,:16)
""", [
    (r[0], r[1], r[2], r[3], r[4], parse_dt(r[5]),
     r[6], r[7], r[8], r[9], r[10],
     r[11], r[12], int(r[13]) if r[13] is not None else 0,
     r[14], r[15])
    for r in matches
])
con.commit()
print(f"  matches {len(matches)}건 삽입")

# ── 5. Users 삽입 ─────────────────────────────────────────────────────────
users = src.execute(text(
    "SELECT id, email, nickname, hashed_password, points, is_admin FROM users"
)).fetchall()

cur.executemany("""
    INSERT INTO users (id, email, nickname, hashed_password, points, is_admin)
    VALUES (:1,:2,:3,:4,:5,:6)
""", [(r[0], r[1], r[2], r[3], r[4], int(r[5])) for r in users])
con.commit()
print(f"  users {len(users)}건 삽입")

# ── 6. Bets 삽입 ──────────────────────────────────────────────────────────
bets = src.execute(text(
    "SELECT id, user_id, match_id, prediction, amount, status, payout FROM bets"
)).fetchall()

if bets:
    cur.executemany("""
        INSERT INTO bets (id, user_id, match_id, prediction, amount, status, payout)
        VALUES (:1,:2,:3,:4,:5,:6,:7)
    """, list(bets))
    con.commit()
print(f"  bets {len(bets)}건 삽입")

src.close()
cur.close()
con.close()
print("\n완료!")
